{{- if .Values.image.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "image.pullSecret.name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "image.pullSecret.config" . }}
{{- end }}
